// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialProject;

namespace TrialProject.Migrations
{
    [DbContext(typeof(PracticeContext))]
    partial class PracticeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrialProject.Entities.User", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int>("Password");

                    b.Property<int>("PhoneNumber");

                    b.Property<string>("Uname");

                    b.Property<string>("UserRole");

                    b.HasKey("UId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrialProjectEntities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("Email");

                    b.Property<int>("HouseNo");

                    b.Property<int>("PinCode");

                    b.Property<string>("State");

                    b.Property<int>("UId");

                    b.Property<string>("city");

                    b.HasKey("AddressId");

                    b.HasIndex("UId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TrialProjectEntities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Item");

                    b.Property<int>("PId");

                    b.Property<int>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int>("Total");

                    b.Property<int>("UId");

                    b.HasKey("CartId");

                    b.HasIndex("PId");

                    b.HasIndex("UId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TrialProjectEntities.Category", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CDetails");

                    b.Property<string>("CName");

                    b.HasKey("CId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TrialProjectEntities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrederPrice");

                    b.Property<int>("Quantity");

                    b.HasKey("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TrialProjectEntities.Product", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CId");

                    b.Property<string>("PImage");

                    b.Property<string>("PName");

                    b.Property<int>("PPrice");

                    b.Property<int>("Quantity");

                    b.HasKey("PId");

                    b.HasIndex("CId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TrialProjectEntities.Address", b =>
                {
                    b.HasOne("TrialProject.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrialProjectEntities.Cart", b =>
                {
                    b.HasOne("TrialProjectEntities.Product", "product")
                        .WithMany()
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrialProject.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrialProjectEntities.Product", b =>
                {
                    b.HasOne("TrialProjectEntities.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
